version: "3.3"
services:
  frontend:
    build: .
    image: frontend
    ports:
      - 5000:5000
    container_name: flask-app
    environment:
      - APP_ENV=development
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    networks:
      - my-net
    depends_on:
      - mongo
  backend:
    build: .
    image: frontend
    ports:
      - 5000:5000
    container_name: flask-app
    environment:
      - APP_ENV=development
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - CACHE_PLUGIN=redis
      - CACHE_PORT=6379
    networks:
      - my-net
  cli:
    build: .
    image: frontend
    ports:
      - 5000:5000
    container_name: flask-app
    environment:
      - APP_ENV=development
    networks:
      - my-net
  mongo:
    image: mvertes/alpine-mongo
    ports:
      - 27017:27017
    networks:
      - my-net
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - my-net

networks:
  my-net:
